name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./mydashboard
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Navigate to the correct directory run migrations and collect static
    - name: Migrate and Collect Static
      working-directory: ./mydashboard   # Add this to specify the correct working directory
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
          
    - name: Run Tests
      run: |
