name: Django CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or use Python version that fits your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Navigate to the correct directory and run migrations and collect static
      - name: Migrate and Collect Static
        working-directory: ./mydashboard   # Add this to specify the correct working directory
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      # Step 5: Run tests
      - name: Run Django tests
        working-directory: ./mydashboard   # Again, specify the correct directory for the test command
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: 
